---
name: pubnub-react-chat-components
version: v0.7.0
scm: github.com/pubnub/react-chat-components
schema: 1
files:
  - dist/index.js
  - dist/index.es.js
changelog:
  - changes:
      - text: MessageList - tooltips showing the authors of message reactions
        type: feature
      - text: Channel/MemberList - truncating long titles and descriptions with ellipses
        type: feature
      - text: Chat - automatic unsubscribes on channels that were removed from the 'channels' option
        type: feature
      - text: Chat - root callbacks (like onMessage) not getting updated after external change
        type: fix
      - text: Chat - root callbacks causing problems with Components when throwing errors internally
        type: fix
      - text: TypingIndicator - showing current user's indicator
        type: fix
      - text: MessageList - inconsistent automatic scrolling behavior
        type: fix
      - text: MessageInput - selecting emojis clears current input
        type: fix
      - text: MessageInput - sending whitespace-only messages
        type: fix
      - text: useChannelMembers and useUserMemberships - fix and refactor event listeners
        type: fix
    date: 2022-01-28
    version: v0.8.0
  - changes:
      - text: MessageInput - wrong spinner icon sizing
        type: fix
      - text: MessageInput - unwanted scrollbar showing up
        type: fix
      - text: MessageInput - textarea sizing after sending multi-line messages
        type: fix
    date: 2021-10-27
    version: v0.7.0
  - changes:
      - text: Major components redesign
        type: feature
      - text: Telemetry
        type: feature
      - text: MemberList - selfText property
        type: feature
      - text: MemberList - on member click callback
        type: feature
      - text: MessageList - automatic 12h/24h time format based on locale
        type: feature
      - text: useUserMemberships - prevent parallel re-fetches
        type: feature
      - text: useChannelMembers - prevent parallel re-fetches
        type: feature
      - text: useUserMemberships - remove reacting to other channel/uuid events
        type: fix
      - text: useChannelMembers - remove reacting to other channel/uuid events
        type: fix
    date: 2021-10-15
    version: v0.6.0
  - changes:
      - text: MemberList present member indicators
        type: feature
      - text: MemberList extra actions renderer
        type: feature
      - text: MessageInput extra actions renderer
        type: feature
      - text: useChannelMembers fetching too many results
        type: fix
    date: 2021-09-06
    version: v0.5.0
  - changes:
      - text: Basic file/image upload and display using Files API
        type: feature
      - text: Changes to the default theme color palette
        type: feature
      - text: Support for message edits/removals and extra actions renderer in MessageList
        type: feature
      - text: Spinner loader for MessageInput send button
        type: feature
      - text: ChannelList extra actions renderer
        type: feature
      - text: Add new disabled state in MessageInput
        type: feature
      - text: Ability to refetch data in useChannelMembers and useUserMemberships
        type: feature
      - text: Renamed Message interface to MessageEnvelope, added StandardMessage and FileMessage
        type: feature
      - text: Improved MessageList scrolling behavior and detection
        type: fix
      - text: useUser and useUserMemberships hook typings
        type: fix
      - text: usePresence hook options memoization
        type: fix
    date: 2021-08-25
    version: v0.4.0
  - changes:
      - text: Remove default subscription to the 'user channel'
        type: feature
    date: 2021-08-09
    version: v0.3.0
  - changes:
      - text: Remove internal emoji picker component
        type: feature
      - text: Add 'refetch' option to usePresence hook
        type: feature
      - text: Remove default welcome messages on MessageList
        type: improvement
      - text: Improve the display of actions/reactions on certain themes
        type: improvement
    date: 2021-04-30
    version: v0.2.0
  - changes:
      - text: Initial public release
        type: feature
    date: 2021-04-09
    version: v0.1.0
