name: Validate

on:
  push:
  workflow_dispatch:

jobs:
  typescript:
    name: TypeScript type checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache React Chat Component dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-yarn-rcc-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-rcc-
          path: '**/node_modules'
      - name: Run types validation
        shell: bash
        run: |
          yarn install --prefer-offline --frozen-lockfile
          yarn run tsc
